// SPDX-FileCopyrightText: 2026 loheagn <loheagn@icloud.com>
// SPDX-License-Identifier: MIT

import { readdir } from "node:fs/promises";
import { homedir } from "node:os";
import path from "node:path";

import { type ProcessRunner, runProcess } from "./process";

const SQLITE_EXECUTABLE = "/usr/bin/sqlite3";
const DATABASE_TIMEOUT_MS = 5_000;
const DATABASE_MAX_BUFFER = 8 * 1024 * 1024;
const STANDARD_THREAD_SOURCES = new Set(["cli", "vscode", "exec", "appServer", "unknown"]);

const CATALOG_QUERY = `
PRAGMA query_only = ON;
SELECT
  c.host_id AS "hostId",
  c.thread_id AS "id",
  c.display_title AS "name",
  c.cwd AS "cwd",
  c.source_created_at AS "createdAt",
  c.source_updated_at AS "updatedAt"
FROM local_thread_catalog AS c
JOIN local_thread_catalog_hosts AS h
  ON h.host_id = c.host_id
WHERE h.host_kind = 'local'
  AND c.missing_candidate = 0
ORDER BY
  c.source_updated_at DESC,
  c.source_created_at DESC,
  c.host_id ASC,
  c.thread_id ASC;
`;

// These are lifecycle and display metadata only. A title may be generated by
// Codex from the first prompt, but the query deliberately omits the preview,
// first_user_message, rollout path, and conversation-content columns.
const STATE_QUERY_PREFIX = `
PRAGMA query_only = ON;
SELECT
  id AS "id",
  cwd AS "cwd",
  title AS "name",
  source AS "source",
`;

const STATE_QUERY_SUFFIX = `
  archived AS "archived"
FROM threads
WHERE archived = 0
  AND source IN ('cli', 'vscode', 'exec', 'appServer', 'unknown');
`;

const STATE_QUERIES = [
  `${STATE_QUERY_PREFIX}
  recency_at_ms AS "recencyAt",
  COALESCE(updated_at_ms, updated_at * 1000) AS "updatedAt",
${STATE_QUERY_SUFFIX}`,
  `${STATE_QUERY_PREFIX}
  recency_at AS "recencyAt",
  updated_at AS "updatedAt",
${STATE_QUERY_SUFFIX}`,
  `${STATE_QUERY_PREFIX}
  updated_at AS "recencyAt",
  updated_at AS "updatedAt",
${STATE_QUERY_SUFFIX}`,
] as const;

export type ThreadSummary = {
  id: string;
  cwd: string;
  cwdCandidates?: string[];
  name: string | null;
  recencyAt: number | null;
  updatedAt: number;
};

type DesktopCatalogRow = {
  hostId: string;
  id: string;
  name: string;
  cwd: string;
  createdAt: number;
  updatedAt: number;
};

type StateThreadRow = {
  id: string;
  cwd: string;
  name: string;
  source: string;
  recencyAt: number | null;
  updatedAt: number;
  archived: number;
};

type StateDatabaseCandidate = {
  path: string;
  layout: "root" | "legacy";
  version: number;
};

type ReadableStateDatabase = StateDatabaseCandidate & {
  rows: StateThreadRow[];
  freshness: number;
};

export interface ListCodexThreadMetadataOptions {
  codexHome: string;
  run?: ProcessRunner;
  sqliteExecutable?: string;
  timeoutMs?: number;
  catalogDatabasePath?: string;
  stateDatabasePath?: string;
  onMetadataWarning?: (warning: string) => void;
}

export async function listCodexThreadMetadata(options: ListCodexThreadMetadataOptions): Promise<ThreadSummary[]> {
  if (options.codexHome.trim().length === 0) {
    throw new Error("A Codex Home directory is required");
  }
  const codexHome = expandTilde(options.codexHome);

  const run = options.run ?? runProcess;
  const sqliteExecutable = options.sqliteExecutable ?? SQLITE_EXECUTABLE;
  const timeoutMs = positiveTimeout(options.timeoutMs, DATABASE_TIMEOUT_MS);
  const catalogDatabasePath = options.catalogDatabasePath ?? path.join(codexHome, "sqlite", "codex-dev.db");
  const stateDatabasePaths = options.stateDatabasePath
    ? [stateDatabaseCandidate(options.stateDatabasePath, "root")]
    : await stateDatabaseCandidates(codexHome);

  let catalogRows: DesktopCatalogRow[] = [];
  try {
    catalogRows = deduplicateCatalogRows(
      (await queryJsonRows(sqliteExecutable, catalogDatabasePath, CATALOG_QUERY, run, timeoutMs)).map(
        parseDesktopCatalogRow,
      ),
    );
  } catch {
    options.onMetadataWarning?.("Codex Desktop 会话目录不可用；尚未写入核心状态库的新会话可能缺失。");
  }

  try {
    const stateRows = await readBestStateDatabase(sqliteExecutable, stateDatabasePaths, run, timeoutMs);
    const stateIds = new Set(stateRows.map(({ id }) => id));
    if (catalogRows.some(({ id }) => !stateIds.has(id))) {
      options.onMetadataWarning?.("Codex Desktop 会话目录尚未同步完成；部分新会话暂时无法验证。");
    }
    return mergeThreadMetadata(stateRows, catalogRows);
  } catch (error) {
    throw new Error("Could not read Codex Desktop thread metadata", { cause: error });
  }
}

function mergeThreadMetadata(
  stateRows: readonly StateThreadRow[],
  catalogRows: readonly DesktopCatalogRow[],
): ThreadSummary[] {
  const stateById = new Map(stateRows.map((row) => [row.id, row]));
  const merged = new Map<string, ThreadSummary>();

  for (const row of stateRows) {
    if (row.archived !== 0 || !STANDARD_THREAD_SOURCES.has(row.source)) {
      continue;
    }
    merged.set(row.id, stateRowToThread(row));
  }

  for (const catalogRow of catalogRows) {
    const stateRow = stateById.get(catalogRow.id);
    if (!stateRow || stateRow.archived !== 0 || !STANDARD_THREAD_SOURCES.has(stateRow.source)) {
      continue;
    }

    const cwdCandidates = uniqueNonBlankStrings([stateRow.cwd, catalogRow.cwd]);
    merged.set(catalogRow.id, {
      id: catalogRow.id,
      cwd: firstNonBlankString([stateRow.cwd, catalogRow.cwd]) ?? "",
      cwdCandidates,
      name: firstNonBlankString([catalogRow.name, stateRow.name]),
      recencyAt: stateRow.recencyAt ?? stateRow.updatedAt,
      updatedAt: Math.max(stateRow.updatedAt, catalogRow.updatedAt),
    });
  }

  return [...merged.values()].sort(compareThreadsByActivity);
}

function stateRowToThread(row: StateThreadRow): ThreadSummary {
  return {
    id: row.id,
    cwd: row.cwd,
    name: row.name,
    recencyAt: row.recencyAt,
    updatedAt: row.updatedAt,
  };
}

async function readBestStateDatabase(
  sqliteExecutable: string,
  candidates: readonly StateDatabaseCandidate[],
  run: ProcessRunner,
  timeoutMs: number,
): Promise<StateThreadRow[]> {
  // A newer filename denotes the authoritative schema generation. Within one
  // generation, a readable root-layout database remains authoritative over a
  // legacy snapshot. Parsed row timestamps disambiguate duplicate candidates
  // without relying on file mtimes, which SQLite WAL writes may not update.
  const versions = [...new Set(candidates.map(({ version }) => version))].sort((left, right) => right - left);
  let lastError: unknown;

  for (const version of versions) {
    const readable: ReadableStateDatabase[] = [];
    for (const candidate of candidates.filter((value) => value.version === version)) {
      try {
        const rows = await readStateRows(sqliteExecutable, candidate.path, run, timeoutMs);
        readable.push({ ...candidate, rows, freshness: stateDatabaseFreshness(rows) });
      } catch (error) {
        lastError = error;
      }
    }

    readable.sort(compareReadableStateDatabases);
    if (readable[0]) {
      return readable[0].rows;
    }
  }

  throw new Error("No compatible current Codex state database was found", { cause: lastError });
}

async function readStateRows(
  sqliteExecutable: string,
  databasePath: string,
  run: ProcessRunner,
  timeoutMs: number,
): Promise<StateThreadRow[]> {
  let lastError: unknown;
  for (const query of STATE_QUERIES) {
    try {
      return (await queryJsonRows(sqliteExecutable, databasePath, query, run, timeoutMs)).map(parseStateThreadRow);
    } catch (error) {
      lastError = error;
    }
  }
  throw new Error("Codex state database has no compatible thread metadata schema", { cause: lastError });
}

async function queryJsonRows(
  sqliteExecutable: string,
  databasePath: string,
  query: string,
  run: ProcessRunner,
  timeoutMs: number,
): Promise<unknown[]> {
  const { stdout } = await run(
    sqliteExecutable,
    ["-readonly", "-json", "-cmd", `.timeout ${timeoutMs}`, databasePath, query],
    { maxBuffer: DATABASE_MAX_BUFFER, timeoutMs },
  );
  if (stdout.trim().length === 0) {
    return [];
  }

  let value: unknown;
  try {
    value = JSON.parse(stdout);
  } catch {
    throw new Error("Codex Desktop metadata database returned invalid JSON");
  }
  if (!Array.isArray(value)) {
    throw new Error("Codex Desktop metadata database returned an invalid result");
  }
  return value;
}

async function stateDatabaseCandidates(codexHome: string): Promise<StateDatabaseCandidate[]> {
  const directories = [codexHome, path.join(codexHome, "sqlite")];
  const discovered: Array<{ directoryIndex: number; file: string; version: number }> = [];

  await Promise.all(
    directories.map(async (directory, directoryIndex) => {
      try {
        for (const entry of await readdir(directory, { withFileTypes: true })) {
          const match = entry.isFile() ? /^state_(\d+)\.sqlite$/.exec(entry.name) : null;
          if (match) {
            discovered.push({ directoryIndex, file: path.join(directory, entry.name), version: Number(match[1]) });
          }
        }
      } catch {
        // Explicit fallback candidates below produce the useful read error.
      }
    }),
  );

  const rootLayout = discovered
    .filter(({ directoryIndex }) => directoryIndex === 0)
    .map(({ file, version }) => ({ path: file, layout: "root" as const, version }));

  const legacyLayout = discovered
    .filter(({ directoryIndex }) => directoryIndex === 1)
    .map(({ file, version }) => ({ path: file, layout: "legacy" as const, version }));
  if (rootLayout.length > 0 || legacyLayout.length > 0) {
    return [...rootLayout, ...legacyLayout];
  }

  return [
    stateDatabaseCandidate(path.join(codexHome, "state_5.sqlite"), "root"),
    stateDatabaseCandidate(path.join(codexHome, "sqlite", "state_5.sqlite"), "legacy"),
  ];
}

function stateDatabaseCandidate(
  databasePath: string,
  layout: StateDatabaseCandidate["layout"],
): StateDatabaseCandidate {
  const match = /^state_(\d+)\.sqlite$/.exec(path.basename(databasePath));
  return { path: databasePath, layout, version: match ? Number(match[1]) : 0 };
}

function stateDatabaseFreshness(rows: readonly StateThreadRow[]): number {
  return rows.reduce((freshness, row) => Math.max(freshness, row.updatedAt), 0);
}

function compareReadableStateDatabases(left: ReadableStateDatabase, right: ReadableStateDatabase): number {
  return (
    Number(right.layout === "root") - Number(left.layout === "root") ||
    right.freshness - left.freshness ||
    left.path.localeCompare(right.path)
  );
}

function deduplicateCatalogRows(rows: readonly DesktopCatalogRow[]): DesktopCatalogRow[] {
  const latest = new Map<string, DesktopCatalogRow>();
  for (const row of rows) {
    const existing = latest.get(row.id);
    if (!existing || row.updatedAt > existing.updatedAt) {
      latest.set(row.id, row);
    }
  }
  return [...latest.values()];
}

function parseDesktopCatalogRow(value: unknown): DesktopCatalogRow {
  if (
    !isJsonObject(value) ||
    typeof value.hostId !== "string" ||
    typeof value.id !== "string" ||
    typeof value.name !== "string" ||
    typeof value.cwd !== "string" ||
    !isFiniteNumber(value.createdAt) ||
    !isFiniteNumber(value.updatedAt)
  ) {
    throw new Error("Codex Desktop returned invalid thread catalog metadata");
  }
  return {
    hostId: value.hostId,
    id: value.id,
    name: value.name,
    cwd: value.cwd,
    createdAt: timestampMilliseconds(value.createdAt),
    updatedAt: timestampMilliseconds(value.updatedAt),
  };
}

function parseStateThreadRow(value: unknown): StateThreadRow {
  if (
    !isJsonObject(value) ||
    typeof value.id !== "string" ||
    typeof value.cwd !== "string" ||
    typeof value.name !== "string" ||
    typeof value.source !== "string" ||
    !isFiniteNumber(value.recencyAt) ||
    !isFiniteNumber(value.updatedAt) ||
    !isFiniteNumber(value.archived)
  ) {
    throw new Error("Codex Desktop returned invalid thread state metadata");
  }
  return {
    id: value.id,
    cwd: value.cwd,
    name: value.name,
    source: value.source,
    recencyAt: value.recencyAt > 0 ? timestampMilliseconds(value.recencyAt) : null,
    updatedAt: timestampMilliseconds(value.updatedAt),
    archived: value.archived,
  };
}

function compareThreadsByActivity(left: ThreadSummary, right: ThreadSummary): number {
  return threadActivityAt(right) - threadActivityAt(left) || left.id.localeCompare(right.id);
}

function threadActivityAt(thread: Pick<ThreadSummary, "recencyAt" | "updatedAt">): number {
  return thread.recencyAt ?? thread.updatedAt;
}

function timestampMilliseconds(value: number): number {
  return value < 10_000_000_000 ? value * 1_000 : value;
}

function firstNonBlankString(values: readonly string[]): string | null {
  return values.find((value) => value.trim().length > 0) ?? null;
}

function uniqueNonBlankStrings(values: readonly string[]): string[] {
  return [...new Set(values.filter((value) => value.trim().length > 0))];
}

function positiveTimeout(value: number | undefined, fallback: number): number {
  const timeout = value ?? fallback;
  if (!Number.isFinite(timeout) || timeout <= 0) {
    throw new Error("timeoutMs must be a positive number");
  }
  return timeout;
}

function expandTilde(value: string): string {
  if (value === "~") {
    return homedir();
  }
  if (value.startsWith("~/") || value.startsWith("~\\")) {
    return path.join(homedir(), value.slice(2));
  }
  return value;
}

function isJsonObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isFiniteNumber(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value);
}
